### ISSUE TITLE
Implement `nextcloud` module on InnproTEST.

### ISSUE THREAD

**Issue by euroblaze** [euroblaze/nextcloud#10]

**Comment by VTV24710** [comment]
Hello @euroblaze , this issue I estimate 1hr but if there is any issue in database can you give me bonus 1hr - 2hr more to fix the error?

**Comment by euroblaze** [comment]
> this issue I estimate 1hr but if there is any issue in database can you give me bonus 1hr - 2hr more to fix the error? 

Let's consolidate NC work on https://github.com/euroblaze/nextcloud/issues/11

Closing this issue. 

Thanks for taking a look , @VTV24710
