### ISSUE TITLE
Login to non-admin Account

### ISSUE THREAD

**Issue by euroblaze** [euroblaze/nextcloud#3]
- [ ] Login into a non-admin account unsuccessful
https://vimeo.com/875548122/6c720b444b

- [ ] Prefer login with a key (instead of username/password).

- [ ] If using user/pass, prefer username to be an **email-address**.

**Comment by holengocquy** [comment]
It depends on how user are created. AppPassword should be generated

**Comment by euroblaze** [comment]
On Thu, 19 Oct 2023 at 20:38, 'holengocquy' via euroblaze Github Common
Account ***@***.***> wrote:

> It depends on how user are created. AppPassword should be generated
>
Screenshot of how and where this should be done will be helpful for
documentation.

Thanks!

**Comment by holengocquy** [comment]
![image](https://github.com/euroblaze/nextcloud/assets/41163310/0999c27b-c6ac-4bf7-bce7-f5566853f81a)

**Comment by euroblaze** [comment]
For closure..

The solution was the use the user's name, not username :))
