### ISSUE TITLE
FileUpload Bug

### ISSUE THREAD

**Issue by euroblaze** [euroblaze/nextcloud#35]
Acute problem.
File Upload is broken.
Is there a log-file we are writing in Odoo for **file transaction processes**?

https://vimeo.com/1018613932/a3a3da1d22

**Comment by euroblaze** [comment]
@VTV24710 
As discussed..

1. Store Attachments independent of `res.company`.
2. No access control imposed on NC files. 
3. Only Odoo Access Rights are imposed on the Odoo modules, fields and documents.

And move the Settings out of `res.company` form view, to _Settings > NextCloud_.

**Comment by VTV24710** [comment]
Hello @euroblaze,
Some note for you on this issue from PROD.
1. Nextcloud Setting
![Image](https://github.com/user-attachments/assets/fb342341-45c2-44b2-961a-2e6090654ca0)
2. We can upload, download from any company
3. PROD result:
![Image](https://github.com/user-attachments/assets/2c172425-384d-4662-af4b-61d59222f3a3)

**Comment by euroblaze** [comment]
@VTV24710 
Thanks for deployement.
Customer messages. Hope their test go perfect..
Closing for now 🙏
